import React, { useContext, useEffect, useState, useMemo } from 'react';
import axios from 'axios';
import { AppContext } from '../../context/AppContext';
import { FaEnvelope, FaPaperPlane, FaBrain, FaTriangleExclamation, FaMoneyBillTrendUp, FaRobot, FaTrashCan, FaChartBar } from 'react-icons/fa6';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar, Line } from 'react-chartjs-2';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

const PinnedChart = ({ chart, token }) => {
  const [dataRows, setDataRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchSqlData = async () => {
      try {
        const res = await axios.post('/api/sql/execute', { sql: chart.sql }, { headers: { Authorization: `Bearer ${token}` }});
        setDataRows(res.data.rows);
      } catch (e) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    };
    fetchSqlData();
  }, [chart.sql, token]);

  const chartData = useMemo(() => {
    if (dataRows.length === 0) return null;
    return {
      labels: dataRows.map(r => r[chart.x_axis]),
      datasets: [{
        label: chart.y_axis,
        data: dataRows.map(r => {
          const val = r[chart.y_axis];
          return typeof val === 'number' ? val : parseFloat(val) || 0;
        }),
        backgroundColor: 'rgba(99, 102, 241, 0.6)',
        borderColor: 'rgb(99, 102, 241)',
        borderWidth: 1,
      }]
    };
  }, [dataRows, chart]);

  return (
    <div className="bg-white/60 dark:bg-slate-900/50 p-4 rounded-xl border border-indigo-50 dark:border-indigo-800/30 mb-4 shadow-sm">
      <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 mb-3">{chart.title}</h4>
      {loading ? (
        <p className="text-xs text-slate-500 animate-pulse">Running live query...</p>
      ) : error ? (
        <p className="text-xs text-rose-500">{error}</p>
      ) : chartData ? (
        <div className="w-full h-48 relative">
          {chart.chart_type === 'Bar' ? (
            <Bar data={chartData} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} />
          ) : (
            <Line data={chartData} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} />
          )}
        </div>
      ) : (
        <p className="text-xs text-slate-500">No data available.</p>
      )}
    </div>
  );
};

const BriefingsTab = () => {
  const { businessData, setGlobalChatPrompt, token, customBriefings, addToast } = useContext(AppContext);
  const [outbox, setOutbox] = useState([]);
  const [pinnedCharts, setPinnedCharts] = useState([]);
  const [emailToSend, setEmailToSend] = useState(null);
  const [emailToDiscard, setEmailToDiscard] = useState(null);
  
  useEffect(() => {
    const fetchOutbox = async () => {
      if (!token) return;
      try {
        const res = await axios.get('/api/outbox', { headers: { Authorization: `Bearer ${token}` }});
        setOutbox(res.data);
      } catch (e) {
        console.error("Error loading outbox", e);
      }
    };
    const fetchPinnedCharts = async () => {
      if (!token) return;
      try {
        const res = await axios.get('/api/charts/pinned', { headers: { Authorization: `Bearer ${token}` }});
        setPinnedCharts(res.data);
      } catch (e) {
        console.error("Error loading pinned charts", e);
      }
    };
    fetchOutbox();
    fetchPinnedCharts();
  }, [token]);

  const handleSendEmail = (index) => {
    // Remove the item from outbox
    const newOutbox = [...outbox];
    newOutbox.splice(index, 1);
    setOutbox(newOutbox);
    
    // Add success toast
    if (addToast) {
      addToast("Email dispatched successfully", "success");
    }
  };

  const handleDiscardEmail = (index) => {
    // Remove the item from outbox
    const newOutbox = [...outbox];
    newOutbox.splice(index, 1);
    setOutbox(newOutbox);
    
    // Add info toast
    if (addToast) {
      addToast("Draft discarded", "info");
    }
  };

  return (
    <div className="animate-fade-in">
      <div className="mb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white">Executive Reports</h2>
            <p className="text-slate-500 dark:text-slate-400">Consolidated strategic reports generated by the executive team.</p>
          </div>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column */}
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 flex items-center gap-2">
                <FaMoneyBillTrendUp className="text-emerald-500" /> Top Pipeline Opportunities
              </h3>
              <button 
                onClick={() => setGlobalChatPrompt("Analyze our current pipeline. Are there any unusually large deals or risks we should be aware of?")}
                className="text-xs px-2.5 py-1.5 bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 hover:bg-blue-100 dark:hover:bg-blue-900/50 rounded-lg flex items-center gap-1.5 transition-colors border border-blue-200 dark:border-blue-800"
              >
                <FaRobot /> Ask AI
              </button>
            </div>
            {businessData ? (
              <div className="space-y-4">
                {businessData.sales_pipeline?.deals
                  ?.filter(d => !d.stage.includes('Closed'))
                  ?.sort((a, b) => b.value - a.value)
                  ?.slice(0, 3)
                  .map((deal, i) => (
                    <div key={i} className="flex justify-between items-center pb-3 border-b border-slate-100 dark:border-slate-700 last:border-0 last:pb-0">
                      <div>
                        <span className="font-bold text-slate-900 dark:text-white block">{deal.client}</span>
                        <span className="text-xs text-slate-500 dark:text-slate-400 uppercase tracking-wide">{deal.stage}</span>
                      </div>
                      <span className="font-bold text-emerald-600 dark:text-emerald-400">
                        ${deal.value.toLocaleString()}
                      </span>
                    </div>
                ))}
              </div>
            ) : (
              <p className="animate-pulse text-slate-500">Loading pipeline data...</p>
            )}
          </div>

          <div className="bg-rose-50 dark:bg-rose-900/10 p-6 rounded-xl border border-rose-200 dark:border-rose-800 shadow-sm">
            <h3 className="text-lg font-semibold text-rose-800 dark:text-rose-300 mb-4 flex items-center gap-2">
              <FaTriangleExclamation /> Critical Action Items
            </h3>
            {businessData ? (
              <ul className="space-y-3">
                {businessData.compliance?.regulatory_risks?.slice(0, 2).map((risk, i) => (
                  <li key={i} className="flex gap-3 text-sm text-rose-700 dark:text-rose-400">
                    <span className="mt-0.5">•</span>
                    <span><strong>{risk.risk_area}:</strong> {risk.description}</span>
                  </li>
                ))}
                {businessData.sales_pipeline?.deals?.filter(d => d.value > 50000 && !d.stage.includes('Closed')).slice(0, 1).map((deal, i) => (
                  <li key={`deal-${i}`} className="flex gap-3 text-sm text-amber-700 dark:text-amber-400">
                    <span className="mt-0.5">•</span>
                    <span><strong>High Value Deal:</strong> {deal.client} is stuck in {deal.stage}. Requires executive sponsor.</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-rose-500 animate-pulse">Scanning for risks...</p>
            )}
          </div>
        </div>

        {/* Middle Column */}
        <div className="space-y-6">
          <div className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 p-6 rounded-xl border border-indigo-100 dark:border-indigo-800/30 shadow-sm relative overflow-hidden">
            <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-indigo-500/10 dark:bg-indigo-500/20 rounded-full blur-2xl"></div>
            <h3 className="text-lg font-semibold text-indigo-900 dark:text-indigo-300 mb-4 flex items-center gap-2 relative z-10">
              <FaBrain className="text-indigo-500" /> AI Strategic Insights
            </h3>
            <div className="space-y-4 relative z-10">
              <div className="bg-white/60 dark:bg-slate-900/50 p-3 rounded-lg border border-indigo-50 dark:border-indigo-800/30 text-sm text-slate-700 dark:text-slate-300">
                <strong className="text-indigo-700 dark:text-indigo-400 block mb-1">Cost Optimization:</strong>
                Based on historical patterns, reducing Q3 marketing spend by 12% will extend runway by 2.4 months with minimal pipeline impact.
              </div>
              <div className="bg-white/60 dark:bg-slate-900/50 p-3 rounded-lg border border-indigo-50 dark:border-indigo-800/30 text-sm text-slate-700 dark:text-slate-300">
                <strong className="text-purple-700 dark:text-purple-400 block mb-1">Market Opportunity:</strong>
                Competitor 'Global Tech' has recently increased pricing. Recommended to run a targeted ad campaign highlighting our cost efficiency.
              </div>
            </div>
          </div>

          <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm">
            <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-4 flex items-center gap-2">
              <i className="fa-solid fa-plug text-slate-400"></i> Active Integrations
            </h3>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center text-blue-600"><i className="fa-brands fa-salesforce"></i></div>
                  <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Salesforce CRM</span>
                </div>
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600"><i className="fa-brands fa-stripe"></i></div>
                  <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Stripe Billing</span>
                </div>
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded bg-orange-100 dark:bg-orange-900/30 flex items-center justify-center text-orange-600"><i className="fa-brands fa-aws"></i></div>
                  <span className="text-sm font-medium text-slate-700 dark:text-slate-300">AWS Infrastructure</span>
                </div>
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
              </div>
            </div>
          </div>

          {pinnedCharts?.length > 0 && (
            <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm mt-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 flex items-center gap-2">
                  <FaChartBar className="text-indigo-500" /> Analyst Dashboards
                </h3>
              </div>
              <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2">
                {pinnedCharts.map((chart) => (
                  <PinnedChart key={chart.id} chart={chart} token={token} />
                ))}
              </div>
            </div>
          )}

          {customBriefings?.length > 0 && (
            <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm mt-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 flex items-center gap-2">
                  <FaBrain className="text-purple-500" /> Saved AI Insights
                </h3>
              </div>
              <div className="space-y-4 max-h-[300px] overflow-y-auto pr-2">
                {customBriefings.map((briefing) => (
                  <div key={briefing.id} className="p-4 bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-700 transition-transform hover:-translate-y-1 hover:shadow-md">
                    <div className="flex justify-between items-start mb-2">
                      <p className="text-sm font-bold text-slate-800 dark:text-slate-200">{briefing.title}</p>
                      <span className="text-xs px-2 py-1 bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400 rounded-full font-semibold">{briefing.date}</span>
                    </div>
                    <p className="text-sm text-slate-600 dark:text-slate-400 whitespace-pre-wrap">{briefing.content}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
        
        {/* Right Column */}
        <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm h-full flex flex-col">
          <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-4 flex items-center gap-2">
            <FaEnvelope className="text-blue-500" /> Executive Outbox
          </h3>
          <div className="space-y-4 flex-1 overflow-y-auto pr-2">
            {outbox.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full text-center p-6 bg-slate-50 dark:bg-slate-800/50 rounded-xl border border-dashed border-slate-300 dark:border-slate-700">
                <div className="w-16 h-16 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mb-4">
                  <FaPaperPlane className="text-slate-400 dark:text-slate-500 text-2xl" />
                </div>
                <h4 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1">Outbox is Empty</h4>
                <p className="text-xs text-slate-500 max-w-[200px]">Any automated email drafts generated by the AI will appear here for your review.</p>
              </div>
            ) : (
              outbox.map((email, i) => (
                <div key={i} className="p-4 bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-700 transition-transform hover:-translate-y-1 hover:shadow-md">
                  <div className="flex justify-between items-start mb-2">
                    <p className="text-sm font-bold text-slate-800 dark:text-slate-200">To: {email.to}</p>
                    <span className="text-xs px-2 py-1 bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400 rounded-full font-semibold">Draft</span>
                  </div>
                  <p className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Subject: {email.subject}</p>
                  <p className="text-xs text-slate-600 dark:text-slate-400 whitespace-pre-wrap font-mono bg-white dark:bg-slate-800 p-2 rounded border border-slate-100 dark:border-slate-700">{email.body}</p>
                  <div className="flex items-center gap-4 mt-3">
                    <button 
                      onClick={() => setEmailToSend(i)}
                      className="text-xs flex items-center gap-1 text-blue-600 hover:text-blue-500 dark:text-blue-400 font-medium"
                    >
                      <FaPaperPlane /> Send Now
                    </button>
                    <button 
                      onClick={() => setEmailToDiscard(i)}
                      className="text-xs flex items-center gap-1 text-rose-600 hover:text-rose-500 dark:text-rose-400 font-medium"
                    >
                      <FaTrashCan /> Discard
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {emailToSend !== null && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4 animate-fade-in">
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl max-w-md w-full border border-slate-200 dark:border-slate-700 overflow-hidden transform scale-100 transition-all">
            <div className="p-6">
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Confirm Send</h3>
              <p className="text-slate-600 dark:text-slate-400 text-sm mb-6">
                Are you sure you want to dispatch this email to <strong>{outbox[emailToSend]?.to}</strong>? This action cannot be undone.
              </p>
              <div className="flex items-center justify-end gap-3">
                <button 
                  onClick={() => setEmailToSend(null)}
                  className="px-4 py-2 text-sm font-semibold text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
                >
                  Cancel
                </button>
                <button 
                  onClick={() => {
                    handleSendEmail(emailToSend);
                    setEmailToSend(null);
                  }}
                  className="px-4 py-2 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-500 rounded-lg flex items-center gap-2 transition-colors"
                >
                  <FaPaperPlane /> Confirm & Send
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {emailToDiscard !== null && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4 animate-fade-in">
          <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl max-w-md w-full border border-slate-200 dark:border-slate-700 overflow-hidden transform scale-100 transition-all">
            <div className="p-6">
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Confirm Discard</h3>
              <p className="text-slate-600 dark:text-slate-400 text-sm mb-6">
                Are you sure you want to discard this email draft? This action cannot be undone.
              </p>
              <div className="flex items-center justify-end gap-3">
                <button 
                  onClick={() => setEmailToDiscard(null)}
                  className="px-4 py-2 text-sm font-semibold text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
                >
                  Cancel
                </button>
                <button 
                  onClick={() => {
                    handleDiscardEmail(emailToDiscard);
                    setEmailToDiscard(null);
                  }}
                  className="px-4 py-2 text-sm font-semibold text-white bg-rose-600 hover:bg-rose-500 rounded-lg flex items-center gap-2 transition-colors"
                >
                  <FaTrashCan /> Discard Draft
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default BriefingsTab;
