# Mock data template for BusinessOS
DEFAULT_BUSINESS_DATA = {
    "company_name": "ScribeFlow Solutions",
    "industry": "B2B SaaS (Automated Documentation)",
    "financials": {
        "cash_balance": 350000,
        "monthly_mrr": 45000,
        "expenses": {
            "payroll": 32000,
            "marketing": 8000,
            "hosting_cloud": 4000,
            "software_licenses": 2000,
            "office_rent": 1500,
            "miscellaneous": 500,
        },
        "historical_performance": [
            {"month": "January", "revenue": 38000, "expenses": 45000},
            {"month": "February", "revenue": 40000, "expenses": 46000},
            {"month": "March", "revenue": 42000, "expenses": 47000},
            {"month": "April", "revenue": 43500, "expenses": 48000},
            {"month": "May", "revenue": 45000, "expenses": 48000},
        ],
    },
    "sales_pipeline": {
        "stages": [
            "Lead",
            "Demo",
            "Proposal",
            "Negotiation",
            "Closed Won",
            "Closed Lost",
        ],
        "deals": [
            {
                "id": "deal_1",
                "name": "Acme Corp Enterprise",
                "value": 25000,
                "stage": "Proposal",
                "probability": 0.6,
                "owner": "Sarah Jenkins",
                "age_days": 45,
            },
            {
                "id": "deal_2",
                "name": "GlobalTech Integration",
                "value": 18000,
                "stage": "Negotiation",
                "probability": 0.8,
                "owner": "Sarah Jenkins",
                "age_days": 60,
            },
            {
                "id": "deal_3",
                "name": "Nova Retail Systems",
                "value": 12000,
                "stage": "Demo",
                "probability": 0.4,
                "owner": "Mike Ross",
                "age_days": 12,
            },
            {
                "id": "deal_4",
                "name": "Apex Consulting",
                "value": 8000,
                "stage": "Lead",
                "probability": 0.2,
                "owner": "Mike Ross",
                "age_days": 5,
            },
            {
                "id": "deal_5",
                "name": "Vortex Finance",
                "value": 30000,
                "stage": "Negotiation",
                "probability": 0.9,
                "owner": "Sarah Jenkins",
                "age_days": 90,
            },
            {
                "id": "deal_6",
                "name": "EcoSphere Logistics",
                "value": 15000,
                "stage": "Closed Won",
                "probability": 1.0,
                "owner": "Mike Ross",
                "age_days": 30,
            },
            {
                "id": "deal_7",
                "name": "Stellar Media",
                "value": 10000,
                "stage": "Closed Lost",
                "probability": 0.0,
                "owner": "Mike Ross",
                "age_days": 40,
            },
        ],
        "average_deal_cycle_days": 42,
    },
    "market_intelligence": {
        "competitors": [
            {
                "name": "DocuGenie",
                "market_share": "32%",
                "pricing": "$49/user/month",
                "strengths": "Rich template library, established brand",
                "weaknesses": "Slow generation, outdated editor",
            },
            {
                "name": "WriteAI Pro",
                "market_share": "18%",
                "pricing": "$29/user/month",
                "strengths": "Fast generation speed, low pricing",
                "weaknesses": "Poor formatting, lacks API integrations",
            },
            {
                "name": "AutoDoc Co",
                "market_share": "12%",
                "pricing": "$99/user/month",
                "strengths": "Excellent API integrations, enterprise grade security",
                "weaknesses": "Complex onboarding, high pricing",
            },
        ],
        "industry_growth_rate": "24% YoY",
        "customer_demographics": "Mid-market software companies and digital agencies",
    },
    "compliance": {
        "gdpr_status": "Compliant (Last Audit: May 2026)",
        "checklist": [
            {
                "item": "Data Processing Agreements (DPA) signed with all sub-processors",
                "status": "Completed",
            },
            {
                "item": "User consent opt-in implemented on all lead capture forms",
                "status": "Completed",
            },
            {
                "item": "Data breach notification procedure established and documented",
                "status": "Completed",
            },
            {
                "item": "Annual employee privacy training completed",
                "status": "Pending (Due: Aug 2026)",
            },
            {"item": "CCPA compliance mapping completed", "status": "In Progress"},
        ],
        "regulatory_risks": [
            {
                "risk_area": "Data Privacy",
                "description": "New EU AI Act requirements demand transparency logs for generated content.",
                "severity": "Medium",
                "mitigation": "Incorporate audit trails into product backend by Q4 2026.",
            }
        ],
    },
}
